FROM python:3.8

WORKDIR /app
COPY ./pollute_main.py ./
COPY ./evaluate.py ./
COPY ./paper_tables.py ./
COPY ./requirements.txt ./
COPY ./pollock_weights.json ./
COPY ./pollock ./pollock
COPY ./sut/utils.py ./sut/utils.py

RUN pip install --no-cache-dir -r requirements.txt

CMD ["echo", "Build completed"]
